apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi-app
  namespace: dev

spec:
  replicas: 3

  selector:
    matchLabels:
      app: fastapi-app

  template:
    metadata:
      labels:
        app: fastapi-app

    spec:
      containers:
      - name: fastapi-app
        image: backend:1.4
        imagePullPolicy: Never

        env:
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: MODEL_NAME

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: fastapi-config
              key: LOG_LEVEL
  